version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
   build:
    jobs:
      # first get the source code and install npm dependencies
      # - cypress/install
      - cypress/run:
          name: Run Cypress tests
          # this avoids installing same dependencies 10 times
          requires:
            - cypress/install
          no-workspace: true
          record: true
          group: 1 machine

          tags: CircleCI
          store_artifacts: true
#          command: npm run ci:run