version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
   build:
    jobs:
      - cypress/install:
           name: Install all dependencies
      - cypress/run:
          name: Run Cypress tests
          requires:
            - Install all dependencies
          no-workspace: true
          record: true
          group: 1 machine

          tags: CircleCI
          store_artifacts: true
#          command: npm run ci:run