version: 2.1
orbs:
  cypress: cypress-io/cypress@2.2.0
workflows:
   build:
    jobs:
      - cypress/install:
           name: Install all dependencies
      - cypress/run:
          name: Run Cypress tests
          requires:
            - Install all dependencies
          parallel: true
          parallelism: 2
          no-workspace: true
          record: true
          group: All tests
          tags: CircleCI
          store_artifacts: true
          command: npm run ci:run