version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
   build:
    jobs:
#      # first get the source code and install npm dependencies
#      - cypress/install
      - cypress/run:
          # this avoids installing same dependencies 10 times
#          requires:
#            - cypress/install
          # Cypress dashboard config
          record: true
          parallel: true
          parallelism: 2
          group: 2 machines

          tags: CircleCI # circleCi tag
          store_artifacts: true # stores cypress/screenshots and cypress/videos artifacts
          command: npm run ci:run # run command using record key for cypress dashboard
          no-workspace: true #skips persisting to workspace